In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv('NYM_batting.csv')
# generate a random array of shape (3, 4)
random_array = np.random.rand(3, 4)
print("Random Array:")
print(random_array)
print(random_array[0])

Random Array:
[[0.14380773 0.2149086  0.74972247 0.07260327]
 [0.10297534 0.93228582 0.75256664 0.24621297]
 [0.22169689 0.1248634  0.81337499 0.53167336]]
[0.14380773 0.2149086  0.74972247 0.07260327]
